[font]
size = 12.0

[font.bold]
family = "ComicShannsMono Nerd Font"

[font.italic]
family = "ComicShannsMono Nerd Font"

[font.normal]
family = "ComicShannsMono Nerd Font"

[window.padding]
x = 0
y = 0
