[colors.normal]
black = "#1e2127"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#ffffff"
white = "#e6efff"
yellow = "#d19a66"

[colors.primary]
background = "#1e2127"
bright_foreground = "#e6efff"
foreground = "#abb2bf"

[font]
size = 10.0

[font.bold]
family = "ComicShannsMono Nerd Font"

[font.italic]
family = "ComicShannsMono Nerd Font"

[font.normal]
family = "ComicShannsMono Nerd Font"

[window]
opacity = 0.85

[window.padding]
x = 0
y = 0
